# Generated by Django 2.1.2 on 2018-10-26 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20181026_1603'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='departamentos',
            table='[DBO].[AUX_Grupo_Segmento]',
        ),
    ]
