# Generated by Django 2.1.2 on 2018-10-26 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20181026_1613'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='departamentos',
            table='[DW].[PREMIO_TIPO_ID]',
        ),
    ]
