# Generated by Django 2.1.2 on 2018-10-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20181026_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Premio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
            ],
            options={
                'db_table': '[DW].[PREMIO_TIPO_ID]',
            },
        ),
        migrations.RemoveField(
            model_name='departamentos',
            name='descricao',
        ),
        migrations.AddField(
            model_name='departamentos',
            name='Ativo',
            field=models.CharField(default=str, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departamentos',
            name='CC_Custo',
            field=models.CharField(default=str, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departamentos',
            name='Grupo',
            field=models.CharField(default=str, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departamentos',
            name='Nom_secao',
            field=models.CharField(default=str, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='departamentos',
            table='[DBO].[AUX_Grupo_Segmento]',
        ),
    ]
