# Generated by Django 2.1.2 on 2018-10-29 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20181029_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamentos',
            old_name='Nom_secao',
            new_name='Descricao',
        ),
    ]
