# Generated by Django 2.1.2 on 2018-10-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20181029_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamentos',
            name='id',
        ),
        migrations.AlterField(
            model_name='departamentos',
            name='CC_Custo',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
