# Generated by Django 2.1.2 on 2018-11-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_auto_20181029_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('CPF', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('NOME', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '[DBO].[V_ML_FUNCIONARIO]',
            },
        ),
    ]
