# Generated by Django 2.1.2 on 2018-11-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_premio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premio',
            old_name='falta_inju',
            new_name='faltas_inju',
        ),
        migrations.RenameField(
            model_name='premio',
            old_name='falta_just',
            new_name='faltas_just',
        ),
        migrations.AddField(
            model_name='premio',
            name='estagio',
            field=models.PositiveIntegerField(default=int),
            preserve_default=False,
        ),
    ]
